import { useMemo, useState, type FormEvent, type ReactElement } from 'react';
import Select from 'react-select';
import type { MultiValue, SingleValue } from 'react-select';
import { MdAdd, MdCancel, MdCheckCircleOutline, MdOutlineImage, MdOutlineSchedule, MdRefresh } from 'react-icons/md';
import type { SocialPublicationState } from '../../../hooks/index.ts';
import type { SocialDraftInput, SocialPlatform } from '../../../utils/types/index.ts';
import { Button } from '../index.ts';

type SelectOption<T extends string> = { label: string; value: T };
const platformLabels: Record<SocialPlatform, string> = { facebook: 'Facebook', instagram: 'Instagram', linkedin: 'LinkedIn' };
const categoryOptions: SelectOption<SocialDraftInput['categorie']>[] = [{ value: 'valeur', label: 'Valeur' }, { value: 'service', label: 'Service' }, { value: 'institutionnelle', label: 'Institutionnelle' }, { value: 'humaine', label: 'Humaine' }, { value: 'actualite', label: 'Actualité' }];
const platformOptions: SelectOption<SocialPlatform>[] = Object.entries(platformLabels).map(([value, label]) => ({ value: value as SocialPlatform, label }));
const emptyText: Record<SocialPlatform, string> = { facebook: '', instagram: '', linkedin: '' };

export function SocialPublicationWorkspace({ state }: { state: SocialPublicationState }): ReactElement {
  const [subject, setSubject] = useState('');
  const [category, setCategory] = useState<SocialDraftInput['categorie']>('valeur');
  const [selectedPlatforms, setSelectedPlatforms] = useState<SocialPlatform[]>(['facebook', 'instagram']);
  const [textes, setTextes] = useState(emptyText);
  const [visualId, setVisualId] = useState<string | null>(null);
  const [notes, setNotes] = useState('');
  const [scheduleValues, setScheduleValues] = useState<Record<string, string>>({});
  const [feedback, setFeedback] = useState<string | null>(null);
  const [isSaving, setIsSaving] = useState(false);
  const visualOptions = useMemo<SelectOption<string>[]>(() => state.visuals.map((visual) => ({ value: visual.fileId, label: visual.name })), [state.visuals]);

  const perform = async (action: () => Promise<void>, success: string) => { setFeedback(null); try { await action(); setFeedback(success); } catch (error: unknown) { setFeedback(error instanceof Error ? error.message : 'Action impossible.'); } };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setIsSaving(true); await perform(async () => { const visual = state.visuals.find((item) => item.fileId === visualId); await state.createDraft({ sujet: subject, categorie: category, plateformes: selectedPlatforms, textes, visuel_drive_id: visual?.fileId || null, visuel_url: visual?.webViewLink || null, visuel_notes: notes || null }); setSubject(''); setTextes(emptyText); setVisualId(null); setNotes(''); }, 'Brouillon enregistré. Il attend maintenant une validation éditoriale.'); setIsSaving(false); };

  return <div className="socialPublicationView__content">
    <section className="socialPublicationView__status" aria-label="État des connexions">{Object.entries(state.platforms).map(([key, item]) => <article key={key} className={`socialPublicationView__status-card socialPublicationView__status-card--${item.state}`}><span>{item.label}</span><strong>{item.state === 'ready' ? 'Connexion prête' : 'Configuration requise'}</strong></article>)}</section>
    <section className="socialPublicationView__panel"><div className="socialPublicationView__panel-header"><MdAdd /><div><h2>Préparer une publication</h2><p>Créez les variantes, choisissez le visuel approuvé puis soumettez le brouillon au contrôle éditorial.</p></div></div><form onSubmit={(event) => void submit(event)} className="socialPublicationView__form"><label className="socialPublicationView__field"><span>Sujet</span><input value={subject} onChange={(event) => setSubject(event.target.value)} maxLength={120} placeholder="Ex. Retour sur notre expertise terrain" required /></label><label className="socialPublicationView__field"><span>Catégorie</span><Select<SelectOption<SocialDraftInput['categorie']>, false> options={categoryOptions} value={categoryOptions.find((option) => option.value === category) ?? null} onChange={(option: SingleValue<SelectOption<SocialDraftInput['categorie']>>) => setCategory(option?.value ?? 'valeur')} isSearchable={false} classNamePrefix="socialSelect" menuPortalTarget={document.body} menuPosition="fixed" /></label><label className="socialPublicationView__field socialPublicationView__wide"><span>Réseaux de diffusion</span><Select<SelectOption<SocialPlatform>, true> options={platformOptions} value={platformOptions.filter((option) => selectedPlatforms.includes(option.value))} onChange={(options: MultiValue<SelectOption<SocialPlatform>>) => setSelectedPlatforms(options.map((option) => option.value))} isMulti classNamePrefix="socialSelect" menuPortalTarget={document.body} menuPosition="fixed" /></label>{selectedPlatforms.map((platform) => <label className="socialPublicationView__field socialPublicationView__wide" key={platform}><span>Texte {platformLabels[platform]}</span><textarea value={textes[platform]} onChange={(event) => setTextes((current) => ({ ...current, [platform]: event.target.value }))} placeholder={`Version ${platformLabels[platform]} de la publication`} required rows={4} /></label>)}<label className="socialPublicationView__field socialPublicationView__wide"><span>Visuel Google Drive</span><Select<SelectOption<string>, false> options={visualOptions} value={visualOptions.find((option) => option.value === visualId) ?? null} onChange={(option: SingleValue<SelectOption<string>>) => setVisualId(option?.value ?? null)} placeholder="Rechercher un visuel dans la bibliothèque" noOptionsMessage={() => 'Aucun visuel disponible'} classNamePrefix="socialSelect" menuPortalTarget={document.body} menuPosition="fixed" required /></label><label className="socialPublicationView__field socialPublicationView__wide"><span>Note visuelle</span><input value={notes} onChange={(event) => setNotes(event.target.value)} maxLength={240} placeholder="Direction artistique, format ou version retenue" /></label><div className="socialPublicationView__form-actions"><Button style="gradient" type="submit" disabled={isSaving}><MdAdd />{isSaving ? 'Enregistrement…' : 'Enregistrer le brouillon'}</Button></div></form></section>
    <section className="socialPublicationView__panel"><div className="socialPublicationView__panel-header socialPublicationView__panel-header--actions"><div><h2>Brouillons éditoriaux</h2><p>{state.isLoading ? 'Chargement des brouillons…' : `${state.drafts.length} brouillon(s) suivi(s) dans le registre partagé.`}</p></div><Button style="white" onClick={() => void state.refresh()}><MdRefresh />Actualiser</Button></div>{(feedback || state.error) && <p className="socialPublicationView__feedback">{feedback || state.error}</p>}<div className="socialPublicationView__drafts">{state.drafts.map((draft) => <article className="socialPublicationView__draft" key={draft.id_brouillon_reseau_social}><div className="socialPublicationView__draft-main"><span className={`socialPublicationView__badge socialPublicationView__badge--${draft.statut}`}>{draft.statut.replace(/_/g, ' ')}</span><strong>{draft.sujet}</strong><p>{draft.plateformes.map((platform) => platformLabels[platform]).join(' · ')}</p></div><div className="socialPublicationView__draft-actions">{draft.statut === 'brouillon' && <Button style="green" onClick={() => void perform(() => state.validateDraft(draft.id_brouillon_reseau_social), 'Brouillon validé.')}><MdCheckCircleOutline />Valider</Button>}{draft.statut === 'valide' && <><input aria-label={`Date de publication de ${draft.sujet}`} type="datetime-local" value={scheduleValues[draft.id_brouillon_reseau_social] ?? ''} onChange={(event) => setScheduleValues((current) => ({ ...current, [draft.id_brouillon_reseau_social]: event.target.value }))} /><Button style="gradient" onClick={() => void perform(() => state.scheduleDraft(draft.id_brouillon_reseau_social, new Date(scheduleValues[draft.id_brouillon_reseau_social]).toISOString()), 'Publication programmée.')}><MdOutlineSchedule />Programmer</Button></>}{['brouillon', 'valide', 'programme'].includes(draft.statut) && <Button style="red" onClick={() => void perform(() => state.cancelDraft(draft.id_brouillon_reseau_social), 'Publication annulée.')}><MdCancel />Annuler</Button>}</div></article>)}</div>{!state.isLoading && state.drafts.length === 0 && <div className="socialPublicationView__empty"><MdOutlineImage /><p>Aucun brouillon en cours. Préparez votre première publication ci-dessus.</p></div>}</section>
  </div>;
}
