import type { ChangeEvent, ReactElement } from 'react';
import { IoAdd, IoDocumentTextOutline, IoSearchOutline } from 'react-icons/io5';
import { MdArrowBack, MdVisibility } from 'react-icons/md';
import type { DocumentationPageViewModel } from '../../../hooks/index.ts';
import { BackToTop, Button, DocumentViewerModal, Header, Modal, SubNav } from '../index.ts';

interface Props { viewModel: DocumentationPageViewModel; }
export function DocumentationContent({ viewModel }: Props): ReactElement {
  const { documents, filters, setFilters, isLoading, error, categories, audiences, canPublish, isUploadOpen, setIsUploadOpen, file, setFile, form, setForm, isUploading, submitUpload, viewer, setViewer, openDocument, navigateBack } = viewModel;
  const changeFilter = (event: ChangeEvent<HTMLInputElement | HTMLSelectElement>): void => setFilters({ ...filters, [event.target.name]: event.target.value });
  const changeForm = (event: ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>): void => setForm({ ...form, [event.target.name]: event.target.value });
  return <div id="documentation"><Header /><SubNav /><main><div className="documentation__container">
    <div className="documentation__back"><Button style="back" onClick={navigateBack}><MdArrowBack /><span>Retour</span></Button></div>
    <div className="documentation__header"><div><p className="documentation__eyebrow">Base de connaissances USV</p><h1>Documentation</h1><p>Procédures, modes opératoires et référentiels opérationnels.</p></div>{canPublish && <Button style="gradient" onClick={() => setIsUploadOpen(true)}><IoAdd /> Publier un document</Button>}</div>
    <section className="documentation__filters" aria-label="Recherche avancée"><div className="documentation__search"><IoSearchOutline /><input name="recherche" value={filters.recherche} onChange={changeFilter} placeholder="Rechercher dans les titres, références, descriptions et mots-clés" /></div><select name="categorie" value={filters.categorie} onChange={changeFilter}><option value="">Toutes les catégories</option>{categories.map((category) => <option key={category}>{category}</option>)}</select><select name="public_cible" value={filters.public_cible} onChange={changeFilter}><option value="">Tous les publics</option>{audiences.map((audience) => <option key={audience}>{audience}</option>)}</select><input type="date" name="date_debut" value={filters.date_debut} onChange={changeFilter} aria-label="Publié à partir du" /><input type="date" name="date_fin" value={filters.date_fin} onChange={changeFilter} aria-label="Publié jusqu’au" /></section>
    {error && <p className="documentation__error">{error}</p>}
    <section className="documentation__table-card">{isLoading ? <p className="documentation__empty">Chargement de la documentation…</p> : documents.length === 0 ? <div className="documentation__empty"><IoDocumentTextOutline /><p>Aucun document ne correspond à ces critères.</p></div> : <table><thead><tr><th>Référence</th><th>Document</th><th>Catégorie</th><th>Public</th><th>Version</th><th>Publié le</th><th aria-label="Consulter" /></tr></thead><tbody>{documents.map((document) => <tr key={document.id_documentation}><td><strong>{document.reference}</strong></td><td><strong>{document.titre}</strong>{document.description && <span>{document.description}</span>}<div className="documentation__tags">{document.mots_cles.map((tag) => <em key={tag}>{tag}</em>)}</div></td><td>{document.categorie}</td><td>{document.public_cible}</td><td>v{document.version}</td><td>{new Date(document.date_publication).toLocaleDateString('fr-FR')}</td><td><button className="documentation__view" onClick={() => void openDocument(document)} title="Consulter le PDF"><MdVisibility /></button></td></tr>)}</tbody></table>}</section>
  </div></main><BackToTop />
  <Modal isVisible={isUploadOpen} onClose={() => setIsUploadOpen(false)} title="Publier une documentation" variant="default"><div className="documentation__upload"><p>Le nom serveur est généré avec la référence afin de respecter la convention de stockage.</p><div className="documentation__form-grid"><label>Référence<input name="reference" value={form.reference} onChange={changeForm} placeholder="MOP-USV-041" /></label><label>Version<input name="version" value={form.version} onChange={changeForm} /></label><label className="documentation__full">Titre<input name="titre" value={form.titre} onChange={changeForm} placeholder="Procédure de…" /></label><label>Catégorie<input name="categorie" value={form.categorie} onChange={changeForm} /></label><label>Public cible<input name="public_cible" value={form.public_cible} onChange={changeForm} /></label><label>Mots-clés<input name="mots_cles" value={form.mots_cles} onChange={changeForm} placeholder="virgule, séparés" /></label><label>Date de publication<input type="date" name="date_publication" value={form.date_publication} onChange={changeForm} /></label><label className="documentation__full">Description<textarea name="description" value={form.description} onChange={changeForm} rows={3} /></label><label className="documentation__full">PDF<input type="file" accept="application/pdf" onChange={(event) => setFile(event.target.files?.[0] || null)} />{file && <small>{file.name}</small>}</label></div><div className="documentation__upload-actions"><Button style="white" onClick={() => setIsUploadOpen(false)}>Annuler</Button><Button style="gradient" onClick={() => void submitUpload()} disabled={isUploading}>{isUploading ? 'Publication…' : 'Publier'}</Button></div></div></Modal>
  {viewer && <DocumentViewerModal isVisible fileName={viewer.fileName} fileType="pdf" fileUrl={viewer.url} onClose={() => setViewer(null)} />}</div>;
}
