import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const EXPECTED_ROUTES = [
  '/',
  'auth',
  'home',
  'mail',
  'mail/list',
  'mail/new',
  'mail/update/:id',
  'mail/convert',
  'booking',
  'commerciaux',
  'commerciaux/notes-direction',
  'commerciaux/mon_planning',
  'commercial',
  'commercial/facturation',
  'commercial/devis',
  'commercial/configuration-antl',
  'operations',
  'operations/vigie',
  'operations/demandes-absence',
  'operations/employes',
  'operations/employes/new',
  'operations/employes/details/:id',
  'operations/employes/:id',
  'operations/postes',
  'operations/postes/new',
  'operations/postes/:id',
  'operations/materiel',
  'operations/commandes',
  'operations/commandes/details/:id',
  'operations/qualite/signalements',
  'operations/qualite/statistiques',
  'operations/qualite/ecoutes',
  'operations/qualite',
  'operations/prospects',
  'operations/prospects/enrichissement',
  'campagnes',
  'campagnes/new',
  'campagnes/:id',
  'operations/prospect/:id/inject',
  'incidents',
  'incidents/declarer',
  'incidents/qualification',
  'incidents/traitement',
  'incidents/traitement/:id',
  'incidents/liste',
  'supervision',
  'supervision/alertes',
  'supervision/alertes/historique',
  'prospects/import',
  'produits',
  'produits/new',
  'produits/:id',
  'paniers',
  'paniers/:idPanier/produits',
  'projets/new',
  'projets/mes_taches',
  'projets/:id/edit',
  'projets/:id/taches/new',
  'projets/:id/taches/:tacheId',
  'projets/:id/taches/:tacheId/edit',
  'projets/:id/taches',
  'projets',
  'projets/:id',
  '*',
] as const;

test('le manifeste de routes reste identique au point de départ de la refactorisation', async () => {
  const source = await readFile('src/App.tsx', 'utf8');
  const routes = Array.from(
    source.matchAll(/<Route\s+path=(?:\{["']([^"']+)["']\}|["']([^"']+)["'])/g),
    (match) => match[1] ?? match[2],
  );

  assert.deepEqual(routes, EXPECTED_ROUTES);
});
