import type { CSSProperties, ReactElement } from 'react';
import { MdCheckCircle, MdError, MdWarning } from 'react-icons/md';
import { useAlerteHistoryRow } from '../../../hooks/index.ts';
import { formatAlerteHistoryDate, formatAlerteHistoryValue } from '../../../utils/scripts/index.ts';
import type { AlerteHistory } from '../../../utils/types/index.ts';
import { ALERTE_STATUT_COLORS, ALERTE_STATUT_LABELS, ALERTE_TYPE_COLORS, ALERTE_TYPE_LABELS } from '../../../utils/types/index.ts';
import { Button } from '../button/index.ts';

interface AlerteHistoryRowProps { alerte: AlerteHistory; onResolve: (id: number, comment: string) => void }

export function AlerteHistoryRow({ alerte, onResolve }: AlerteHistoryRowProps): ReactElement {
  const viewModel = useAlerteHistoryRow(alerte, onResolve);
  const statusIcon = alerte.statut === 'active' ? <MdError className="alertesHistoryRow__status-icon alertesHistoryRow__status-icon--error" /> : alerte.statut === 'resolue' ? <MdCheckCircle className="alertesHistoryRow__status-icon alertesHistoryRow__status-icon--success" /> : <MdWarning className="alertesHistoryRow__status-icon alertesHistoryRow__status-icon--warning" />;
  return <article className={`alertesHistoryRow alertesHistoryRow--${alerte.statut}`}><div className="alertesHistoryRow__status">{statusIcon}</div><div className="alertesHistoryRow__type"><span className="alertesHistoryRow__type-badge" style={{ backgroundColor: ALERTE_TYPE_COLORS[alerte.type_alerte] } as CSSProperties}>{ALERTE_TYPE_LABELS[alerte.type_alerte]}</span></div><div className="alertesHistoryRow__statut"><span className="alertesHistoryRow__statut-badge" style={{ backgroundColor: ALERTE_STATUT_COLORS[alerte.statut] } as CSSProperties}>{ALERTE_STATUT_LABELS[alerte.statut]}</span></div><div className="alertesHistoryRow__valeur"><span className={alerte.derniere_valeur === null ? 'alertesHistoryRow__valeur-na' : 'alertesHistoryRow__valeur-value'}>{formatAlerteHistoryValue(alerte)}</span></div><div className="alertesHistoryRow__dates">{formatAlerteHistoryDate(alerte.date_declenchement) && <div className="alertesHistoryRow__date"><span className="alertesHistoryRow__date-label">Déclenchement :</span><span className="alertesHistoryRow__date-value">{formatAlerteHistoryDate(alerte.date_declenchement)}</span></div>}{formatAlerteHistoryDate(alerte.date_resolution) && <div className="alertesHistoryRow__date"><span className="alertesHistoryRow__date-label">Résolution :</span><span className="alertesHistoryRow__date-value">{formatAlerteHistoryDate(alerte.date_resolution)}</span></div>}</div><div className="alertesHistoryRow__commentaire">{viewModel.isEditing ? <div className="alertesHistoryRow__commentaire-edit"><input type="text" value={viewModel.comment} onChange={(event) => viewModel.setComment(event.target.value)} placeholder="Ajouter un commentaire..." /><div className="alertesHistoryRow__commentaire-actions"><Button style="orange" onClick={viewModel.resolve}>Enregistrer</Button><Button style="grey" onClick={viewModel.cancel}>Annuler</Button></div></div> : <div className="alertesHistoryRow__commentaire-display">{alerte.commentaire ? <p>{alerte.commentaire}</p> : <span className="alertesHistoryRow__no-commentaire">Aucun commentaire</span>}</div>}</div><div className="alertesHistoryRow__actions">{alerte.statut === 'active' && !viewModel.isEditing && <Button style="green" onClick={viewModel.startEditing}><MdCheckCircle /> Résoudre</Button>}</div></article>;
}
